
//Bruker
export const HENT_BRUKER_INFORMASJON = 'HENT_BRUKER_INFORMASJON';
export const HENT_BRUKER_INFORMASJON_SUCCESS = 'HENT_BRUKER_INFORMASJON_SUCCESS';
export const HENT_BRUKER_INFORMASJON_FAILURE = 'HENT_BRUKER_INFORMASJON_FAILURE';
export const VIS_PROFIL_POPUP = 'VIS_PROFIL_POPUP';
export const IKKE_AUTORISERT_INNLOGGING = 'IKKE_AUTORISERT_INNLOGGING';
export const TILGANG_TIL_API = 'TILGANG_TIL_API';
export const IKKE_AUTENTISERT = 'IKKE_AUTENTISERT';
export const GENERELL_FEILMELDING_INNLOGGING = 'GENERELL_FEILMELDING_INNLOGGING';